"""update users

Revision ID: 688ab3ff3949
Revises: a487fe4416b6
Create Date: 2024-09-04 17:15:52.576770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688ab3ff3949'
down_revision: Union[str, None] = 'a487fe4416b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippet', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'snippet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snippet', type_='foreignkey')
    op.drop_column('snippet', 'user_id')
    # ### end Alembic commands ###
