"""Initial migration

Revision ID: 927de51fd480
Revises: d9ad91fed54e
Create Date: 2024-08-25 18:45:36.554393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927de51fd480'
down_revision: Union[str, None] = 'd9ad91fed54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snippet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snippet_id'), 'snippet', ['id'], unique=False)
    op.drop_index('ix_Snippet_id', table_name='Snippet')
    op.drop_table('Snippet')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Snippet',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Snippet_pkey')
    )
    op.create_index('ix_Snippet_id', 'Snippet', ['id'], unique=False)
    op.drop_index(op.f('ix_snippet_id'), table_name='snippet')
    op.drop_table('snippet')
    # ### end Alembic commands ###
